name: Build JAR with Gradle

on: [push] # 也可以是 pull_request 等其他事件

jobs:
  build:
    runs-on: ubuntu-latest # 定义运行环境

    steps:
      - uses: actions/checkout@v4 # 检出代码

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21' # 设置 JDK 版本
          distribution: 'temurin' # OpenJDK distribution

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew jar # 编译项目并打包 JAR 文件

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: McServer-Guard-Latest # Artifact 名称
          path: build/libs/*.jar # Artifact 路径